### ISSUE TITLE
Repo Should have Release Versions

### ISSUE THREAD

**Issue by moha297** [tonycoco/heroku-buildpack-ember-cli#100]
A current update on master broke my deploy. I think there should be releases tagged for this repo.

Since it is so widely used, it would provision us to ensure deployments are not broken or we can push a quick fix if needed by tagging the prior revision

**Comment by tonycoco** [comment]
Great idea. I'll start tagging releases.

**Comment by tonycoco** [comment]
See the fix: #102

**Comment by moha297** [comment]
@tonycoco  Could you publish a release at the version before the performance improvements and one after the same. That would be really helpful to keep my production env stable.

**Comment by tonycoco** [comment]
Sure thing... 1 sec.

**Comment by tonycoco** [comment]
I've tagged pre-performance release as `0.9.0` and post-performance as `1.0.0`

**Comment by moha297** [comment]
Thanks. Works...
