### ISSUE TITLE
Bower: command not found

### ISSUE THREAD

**Issue by alexgb** [tonycoco/heroku-buildpack-ember-cli#103]
Recently started getting errors during deployment about missing bower command:

```
remote: -----> Pruning cached bower dependencies not specified in bower.json
remote:        /tmp/buildpack_0318f0c377735568790ff48e00314657/bin/compile: line 186: bower: command not found
remote: 
remote:  !     Push rejected, failed to compile Ember CLI app
remote: 
```

Relevant line from compile script:
https://github.com/tonycoco/heroku-buildpack-ember-cli/blob/master/bin/compile#L186

Possibly related to this change from two days ago https://github.com/tonycoco/heroku-buildpack-ember-cli/commit/3df07aa8b258e5016181ad1522a3d07011046e07 though I can't see anything obviously wrong.

**Comment by alexgb** [comment]
Fixed using `heroku config:set REBUILD_ALL=true`

**Comment by moha297** [comment]
@tonycoco Thanks for the fixes and updates

**Comment by ryudice** [comment]
@alexgb Thanks for posting the fix, just encountered this issue.

**Comment by makmanalp** [comment]
I just encountered this issue. Maybe we should reopen this. Is doing `heroku config:set REBUILD_ALL=true` really a fix? It seems more like a workaround. We don't want all the packages to be reinstalled every build, right?
