### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by erichonkanen** [tonycoco/heroku-buildpack-ember-cli#107]
Hello,

I have been using this for quite awhile but this morning I pushed up to my heroku app and was getting new error saying bower command not found (nothing changed in my bower/package.json)

I then found the notes in the README from 10 days ago about purging the cache and tried that to see if it would work. Now when I pushed the app up to heroku it doesn't work and Im not exactly sure what is going on.

Here is the traceback...

Any suggestions greatly appreciated!

http://dpaste.com/1KAXNZN#wrap

**Comment by allthesignals** [comment]
I started seeing this as well. I usually have to try again and it deploys correctly.

**Comment by erichonkanen** [comment]
ok yeah I tried again and it worked! phew

**Comment by allthesignals** [comment]
It's still kind of annoying, might still be worth remaining an open issue. I'm kind of curious why it does this.

**Comment by erichonkanen** [comment]
ugh its not working again now! this is the original error I get when pushing to my heroku account (that previously has worked for the past 6 months)

```
-----> Fetching custom git buildpack... done
-----> Ember CLI app detected
-----> Exporting config vars to environment
-----> Building environment: production
       PRO TIP: Avoid using semver ranges starting with '>' in engines.node
       See https://devcenter.heroku.com/articles/nodejs-support
-----> Requested node range:  >= 0.10.0
-----> Resolved node version: 4.1.2
-----> Downloading and installing node
-----> Using default npm version: 2.14.4
-----> Downloading and installing nginx
-----> Adding boot script
-----> Copying configs
-----> Restoring node_modules directory from cache
-----> Restoring bower_components directory from cache
-----> Bower already exists
-----> Pruning cached dependencies not specified in package.json
       unbuild bower@1.5.3
-----> Pruning cached bower dependencies not specified in bower.json
       /tmp/buildpack_3c4f4991f1f8efbe46059d480fa35e63/bin/compile: line 186: bower: command not found
 !     Push rejected, failed to compile Ember CLI app
```

**Comment by josepjaume** [comment]
Having this issue as well. Strange. Maybe it's because bower has been updated?

**Comment by tonycoco** [comment]
Bower locked to 1.5.3 from #110 ...closing for now
