### ISSUE TITLE
node-sass causing build to fail

### ISSUE THREAD

**Issue by artsmc** [tonycoco/heroku-buildpack-ember-cli#108]
also found this issue here:
https://github.com/sass/node-sass/issues/13

not sure if its related but I'm seeing the same stuff:
 npm WARN deprecated pangyp@2.3.2: use node-gyp@3+, it does all the things
remote:        
remote:        > node-sass@2.1.1 install /tmp/build_b39be4c794f31269d06be6cd1e5721fa/node_modules/ember-cli-sass/node_modules/broccoli-sass-source-maps/node_modules/node-sass
remote:        > node scripts/install.js
remote:        
remote:        Can not download file from https://raw.githubusercontent.com/sass/node-sass-binaries/v2.1.1/linux-x64-node-4.2/binding.node

**Comment by tonycoco** [comment]
I'll look into this. I just deployed using node-sass and didn't see this issue

**Comment by artsmc** [comment]
I will look into it as well, this is my package.json if it makes a difference, let me know if you see something off.
```
{
  "name": "kitchenninja",
  "version": "0.0.0",
  "description": "Small description for kitchenninja goes here",
  "private": true,
  "directories": {
    "doc": "doc",
    "test": "tests"
  },
  "scripts": {
    "start": "ember server",
    "build": "ember build",
    "test": "ember test"
  },
  "repository": "",
  "engines": {
    "node": ">= 0.10.0"
  },
  "author": "",
  "license": "MIT",
  "devDependencies": {
    "broccoli-asset-rev": "^2.0.2",
    "ember-cli": "1.13.5",
    "ember-cli-app-version": "0.4.0",
    "ember-cli-babel": "^5.0.0",
    "ember-cli-content-security-policy": "0.4.0",
    "ember-cli-dependency-checker": "^1.0.0",
    "ember-cli-htmlbars": "0.7.9",
    "ember-cli-htmlbars-inline-precompile": "^0.1.1",
    "ember-cli-ic-ajax": "0.2.1",
    "ember-cli-inject-live-reload": "^1.3.0",
    "ember-cli-qunit": "0.3.18",
    "ember-cli-release": "0.2.3",
    "ember-cli-sri": "^1.0.1",
    "ember-cli-uglify": "^1.0.1",
    "ember-cli-sass": "^3.2.2",
    "ember-data": "1.13.7",
    "ember-disable-proxy-controllers": "^1.0.0",
    "ember-cli-concat": "1.0.1",
    "ember-cli-document-title": "0.0.3",
    "ember-cli-find-cached": "0.0.1",
    "ember-cli-pace": "0.0.15",
    "ember-export-application-global": "^1.0.3"
  }
}
```

**Comment by tonycoco** [comment]
Can you try to update to the latest `ember-cli-sass`? I have...

`"ember-cli-sass": "^4.2.0"`

**Comment by artsmc** [comment]
Looks like that did the trick! thanks
