### ISSUE TITLE
Bower not found error

### ISSUE THREAD

**Issue by jgadbois** [tonycoco/heroku-buildpack-ember-cli#113]
When I push my app I get:

```
remote: -----> Pruning cached bower dependencies not specified in bower.json
remote:        /tmp/buildpack20151101-165-1wbcvl4/bin/compile: line 186: bower: command not found
remote:
remote:  !     Push rejected, failed to compile Ember CLI app
remote:
```

Higher up in the logs it says:

```
remote: -----> Bower already exists
```

It works if I rebuild everything.  Any ideas?

**Comment by josepjaume** [comment]
Happening to me as well for the last few weeks.

**Comment by SeyZ** [comment]
+1 same problem. I needed to add the `REBUILD_ALL=true` to fix it.

**Comment by drdispatch** [comment]
Same here!

**Comment by seawatts** [comment]
Same here :+1:

**Comment by bdmac** [comment]
Kinda makes the REBUILD_ALL flag a bit confusing as every time I deploy I have to set that flag so far.

**Comment by jgadbois** [comment]
Does anyone know if this repo is still being maintained?

**Comment by seawatts** [comment]
`REBUILD_ALL=true` fixed it for me.

**Comment by seawatts** [comment]
@jgadbois no idea...

**Comment by tonycoco** [comment]
@jgadbois I'm still working on it. Unfortunately, I started a new job and haven't been using Ember at all. Thus, cutting down my tinkering time on it. But, I have a local branch to clean up the codebase and work on a v2 of this buildpack. I'll be pushing it out as soon as I finish it, but until then, pull requests are welcome to fix any and all issues here.

Thanks!

**Comment by tonycoco** [comment]
Another solution is to add in `bower` to the `package.json` for the NPM install, right?

**Comment by jgadbois** [comment]
Thanks for the update @tonycoco !  I'll try adding bower to the package.json that's a good idea.

**Comment by jgadbois** [comment]
FYI adding `bower` to `package.json` didn't fix the problem for me.

**Comment by josepjaume** [comment]
It fixed it for me using specifically the `1.5.3` version (not higher ones).

**Comment by jgadbois** [comment]
@josepjaume did you rebuild from scratch with bower in the `package.json` for the first run?

**Comment by kenglxn** [comment]
May be related to/affected by #123
