### ISSUE TITLE
Set custom path in ember app that points to admin site on another heroku instance

### ISSUE THREAD

**Issue by erichonkanen** [tonycoco/heroku-buildpack-ember-cli#126]
Hello,

How could I do e.g. http://myapp.com/admin/ -> http://\<my-backend-herokuapp\>.com/admin/

Do I need to add a custom nginx file in config/ and then set a custom location for /admin/ ?

Thanks!

**Comment by tonycoco** [comment]
Yep, that would probably work if you set up a custom nginx config
