### ISSUE TITLE
Use different nginx binary?

### ISSUE THREAD

**Issue by danconnell** [tonycoco/heroku-buildpack-ember-cli#131]
I need to use nginx with perl or lua to perform a custom redirect (redirect URLs with uppercase to lowercase), so I need to swap out the nginx binary for a different one.

I've tried building my own nginx binary and uploading it and using that, but I don't think one compiled on OSX is going to work on Heroku since I keep getting parsing errors on a nginx.conf I can run locally.

What's the best way to do this? I can't seem to make any progress on it.

**Comment by tonycoco** [comment]
You can look into: https://github.com/tonycoco/heroku-buildpack-ember-cli/blob/master/bin/compile for how to get a binary compiled.

**Comment by danconnell** [comment]
Yes, I was looking there, and I tried using my own binary, but it didn't seem to run on Heroku. I was asking more if you know how the existing binary that is being used was compiled?

Ideally I can replicate that and just add in perl or lua.

**Comment by tonycoco** [comment]
Ahh. I remember I used: https://github.com/ryandotsmith/nginx-buildpack/blob/master/scripts/build_nginx.sh

**Comment by danconnell** [comment]
Thanks!
