### ISSUE TITLE
NGINX with Perl Module

### ISSUE THREAD

**Issue by nicolo** [tonycoco/heroku-buildpack-ember-cli#135]
Is there a way to enable the perl module through this build pack?

I need it to lowercase uris in the nginx config by including
perl_modules perl/lib;

**Comment by danconnell** [comment]
I needed to do the same thing so I used Lua to accomplish it. You can see how I did that by using OpenResty here: https://github.com/tonycoco/heroku-buildpack-ember-cli/issues/134

**Comment by nicolo** [comment]
Thanks! I was able to get it to work.
