### ISSUE TITLE
Run `bower install` to install missing dependencies.

### ISSUE THREAD

**Issue by johnunclesam** [tonycoco/heroku-buildpack-ember-cli#136]
I'm on a new heroku app and with a new ember-cli app.

After deploy `heroku logs -t` tell me this:

```
ember server

Process exited with status 1
State changed from starting to crashed

Missing bower packages:
Package: ember
  * Specified: ~2.7.0
  * Installed: (not installed)

Package: ember-cli-shims
  * Specified: 0.1.1
  * Installed: (not installed)

Package: ember-qunit-notifications
  * Specified: 0.1.0
  * Installed: (not installed)

Run `bower install` to install missing dependencies.
```

It seems to skip at all the building of bower dependencies. It install only che npm dependencies. Why?

**Comment by anpenava** [comment]
did you find answer I have similar problem :/

`> lunchlist@0.0.0 test /home/ubuntu/lunchlist
> ember test


Missing bower packages: 
Package: ember
  * Specified: ~2.10.0
  * Installed: (not installed)

Package: ember-cli-shims
  * Specified: 0.1.3
  * Installed: (not installed)

Package: firebase
  * Specified: ^3.0.0
  * Installed: (not installed)

Package: moment
  * Specified: ^2.17.1
  * Installed: (not installed)

Package: showdown
  * Specified: ^1.6.4
  * Installed: (not installed)

Package: bootstrap
  * Specified: ^3.3.7
  * Installed: (not installed)

Run `bower install` to install missing dependencies.`

**Comment by rupsk1607** [comment]
I'am also facing the same problem.
