### ISSUE TITLE
Thoughts on supporting yarn as well as npm?

### ISSUE THREAD

**Issue by steveklabnik** [tonycoco/heroku-buildpack-ember-cli#139]
I'm looking to move my projects to yarn. Is there any opposition to adding support for it in this buildpack? I'm willing to send a PR, but wanted to know if it's likely to be accepted or not.

**Comment by tonycoco** [comment]
Yes, for sure! Send the PR along and I'll merge asap.

**Comment by tonycoco** [comment]
Also, check out the official Heroku buildpack here: https://github.com/heroku/heroku-buildpack-emberjs – I've since deprecated this build pack in favor of it.

**Comment by steveklabnik** [comment]
Great!

I did see that you did that, but it seems that that one is also experimental, and we've been using this one in production for a while, so I'm still okay with this for now. No worries though!
