### ISSUE TITLE
Deprecation 

### ISSUE THREAD

**Issue by jholt1** [tonycoco/heroku-buildpack-ember-cli#141]
Thanks for you amazing build pack! I was wondering what is the reason for the deprecation. Is it that you are no longer supporting it, it is missing key features or because heroku is making theirs? 

I ask this because heroku still state that their build pack is experimental.

**Comment by tonycoco** [comment]
I just want to follow the community into the Heroku official build pack. I'll probably continue to patch this buildpack when needed.
