### ISSUE TITLE
How to set the app directory?

### ISSUE THREAD

**Issue by hugoruscitti** [tonycoco/heroku-buildpack-ember-cli#143]
Hi!, i use this buildpack succesfully with some ember apps, but today i want to use in a diferent stage: i have a repo with two main directories "frontend" and "backend". The ember app was copy on the 'frontend' directory, but when a want to deploy to dokku i don't find any way to indicate to dokku that some command like "cd frontend" is needed to deploy correctly.

I think i need to set some hook or set a setting value first, but i don't find any way to do this.

Any suggestions?

thanks!

**Comment by tonycoco** [comment]
Best way would be to deploy them to two different Heroku apps.
