### ISSUE TITLE
Error when pushing latest version of ember-cli

### ISSUE THREAD

**Issue by beeekind** [tonycoco/heroku-buildpack-ember-cli#32]
I've recently updated my ember-cli project and when I tried to push it to Heroku received this error. Any ideas? Thanks.

"-----> Pruning cached bower dependencies not specified in bower.json
-----> Caching node_modules directory for future builds
-----> Cleaning up node-gyp and npm artifacts
bower ember-cli-shims#0.0.2   mismatch Version declared in the json (0.0.1) is different than the resolved one (0.0.2)
bower loader#1.0.0            mismatch Version declared in the json (0.0.0) is different than the resolved one (1.0.0)
bower ember-qunit-notifications#^0.0.3         mismatch Version declared in the json (0.0.2) is different than the resolved one (0.0.3)
bower handlebars#~1.3.0                    invalid-meta handlebars is missing "ignore" entry in bower.json
bower qunit#~1.12.0                        invalid-meta qunit is missing "main" entry in bower.json
bower qunit#~1.12.0                        invalid-meta qunit is missing "ignore" entry in bower.json
bower ember#1.6.1                          invalid-meta ember is missing "ignore" entry in bower.json
bower ember-qunit#~0.1.8                   invalid-meta ember-qunit is missing "main" entry in bower.json
bower ember-localstorage-adapter#~0.4.0        mismatch Version declared in the json (0.3.2) is different than the resolved one (0.4.0)
bower ember-data#>= 1.0.0-beta.6           invalid-meta ember-data is missing "ignore" entry in bower.json
bower ember-data#~1.0.0-beta.7             invalid-meta ember-data is missing "ignore" entry in bower.json
bower ember#>= 1.7.0                       invalid-meta ember is missing "ignore" entry in bower.json
bower                                         ECONFLICT Unable to find suitable version for ember

 !     Push rejected, failed to compile Ember CLI app
"

**Comment by jme783** [comment]
Having this issue here myself. Able to run `ember build`, `npm install`, and `bower install` all without any reported conflicts. Here is my stack trace:
```
remote: bower ember-easyForm#*    invalid-meta ember-easyForm is missing "ignore" entry in bower.json
remote: bower sinon#*             invalid-meta sinon is missing "ignore" entry in bower.json
remote: bower loader.js#1.0.1         mismatch Version declared in the json (0.0.0) is different than the resolved one (1.0.1)
remote: bower ember-mocha#~0.4.0  invalid-meta ember-mocha is missing "main" entry in bower.json
remote: bower ember-simple-auth#0.7.3     invalid-meta ember-simple-auth is missing "ignore" entry in bower.json
remote: bower handlebars#~1.3.0           invalid-meta handlebars is missing "ignore" entry in bower.json
remote: bower ember#1.8.1                 invalid-meta ember is missing "ignore" entry in bower.json
remote: bower ember#>= 1.9.0              invalid-meta ember is missing "ignore" entry in bower.json
remote: bower ember#>= 1.10.0             invalid-meta ember is missing "ignore" entry in bower.json
remote: bower                                ECONFLICT Unable to find suitable version for ember-data
remote:
remote:  !     Push rejected, failed to compile Ember CLI app
remote:
remote: Verifying deploy...
remote:
remote: !       Push rejected to [app name].
remote:
```

Any ideas?

**Comment by jme783** [comment]
For anyone running into this issue, the way to resolve version dependencies is to delete your entire `bower_components` directory first with `rm -rf bower_components`, then re-run `bower install` to install all of your bower dependencies from scratch. This helped me identify incompatible versions in my bower components.

**Comment by nanaewusi** [comment]
Hi, I'm having this issue myself. `ember build` `npm install` and `bower install` all run without any problems errors locally, but I'm having problems deploying to heroku. Here is my stack trace:

    remote: -----> Building Ember CLI application production distribution
    remote:        version: 0.2.0-beta.1
    remote:        Could not find watchman, falling back to NodeWatcher for file system events
    remote:        BuildingBuilding.Cleanup error.
    remote:        undefined is not a function
    remote:        TypeError: undefined is not a function
    remote:        at Function.rimrafSync        
                        (/tmp/build_fa5294c3ed68e0b7c3790d3f26f551b3/node_modules/ember- 
                         cli/node_modules/broccoli-caching-writer/node_modules/rimraf/rimraf.js:262:13)
    remote:         at ConfigLoader.CachingWriter.cleanup  
                         (/tmp/build_fa5294c3ed68e0b7c3790d3f26f551b3/node_modules/ember-
                         cli/node_modules/broccoli-caching-writer/index.js:114:10)
    remote:         at cleanupTree   
                         (/tmp/build_fa5294c3ed68e0b7c3790d3f26f551b3/node_modules/ember-
                         cli/node_modules/broccoli/lib/builder.js:128:19)
    remote:         at /tmp/build_fa5294c3ed68e0b7c3790d3f26f551b3/node_modules/ember-   
                         cli/node_modules/promise-map-series/index.js:11:14
    remote:         at lib$rsvp$$internal$$tryCatch  
                         (/tmp/build_fa5294c3ed68e0b7c3790d3f26f551b3/node_modules/ember- 
                         cli/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:489:16)
    remote:         at lib$rsvp$$internal$$invokeCallback 
                         (/tmp/build_fa5294c3ed68e0b7c3790d3f26f551b3/node_modules/ember-
                         cli/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:501:17)
    remote:          at lib$rsvp$$internal$$publish  
                          (/tmp/build_fa5294c3ed68e0b7c3790d3f26f551b3/node_modules/ember-  
                          cli/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:472:11)
    remote:          at lib$rsvp$asap$$flush  
                          (/tmp/build_fa5294c3ed68e0b7c3790d3f26f551b3/node_modules/ember-
                          cli/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:1290:9)
    remote:          at process._tickCallback (node.js:355:11)
    remote:          Build failed.
    remote:          undefined is not a function
    remote:          TypeError: undefined is not a function
    remote:          at rimraf (/tmp/build_fa5294c3ed68e0b7c3790d3f26f551b3/node_modules/ember-
                          cli/node_modules/broccoli-caching-writer/node_modules/rimraf/rimraf.js:57:13)
    remote:          at lib$rsvp$node$$tryApply 
                          (/tmp/build_fa5294c3ed68e0b7c3790d3f26f551b3/node_modules/ember-
                          cli/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:1467:11)
    remote:          at lib$rsvp$node$$handleValueInput 
                          (/tmp/build_fa5294c3ed68e0b7c3790d3f26f551b3/node_modules/ember-
                          cli/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:1567:20)
    remote:          at fn (/tmp/build_fa5294c3ed68e0b7c3790d3f26f551b3/node_modules/ember-
                          cli/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:1555:18)
    remote:          at /tmp/build_fa5294c3ed68e0b7c3790d3f26f551b3/node_modules/ember-
                          cli/node_modules/broccoli-caching-writer/index.js:100:14
    remote:          at lib$rsvp$$internal$$tryCatch   
                          (/tmp/build_fa5294c3ed68e0b7c3790d3f26f551b3/node_modules/ember-
                          cli/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:489:16)
    remote:          at lib$rsvp$$internal$$invokeCallback 
                          (/tmp/build_fa5294c3ed68e0b7c3790d3f26f551b3/node_modules/ember-
                          cli/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:501:17)
    remote:          at lib$rsvp$$internal$$publish 
                          (/tmp/build_fa5294c3ed68e0b7c3790d3f26f551b3/node_modules/ember-
                          cli/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:472:11)
    remote:          at lib$rsvp$asap$$flush 
                          (/tmp/build_fa5294c3ed68e0b7c3790d3f26f551b3/node_modules/ember-
                          cli/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:1290:9)
    remote:          at process._tickCallback (node.js:355:11)
    remote:
    remote:  !     Push rejected, failed to compile Ember CLI app
    remote:
    remote: Verifying deploy...
    remote:
    remote: !	Push rejected to grocers-web-staging.
    remote:
    To https://git.heroku.com/grocers-web-staging.git
     ! [remote rejected] master -> master (pre-receive hook declined)
    error: failed to push some refs to 'https://git.heroku.com/grocers-web-staging.git

Any ideas?

**Comment by davidgoli** [comment]
Also seeing this. Deleting bower_components and reinstalling did not reveal any conflicts.

**Comment by tonycoco** [comment]
Please make sure you follow the steps...

Try [troubleshooting](https://github.com/tonycoco/heroku-buildpack-ember-cli#troubleshooting).
Try [clearing your Heroku cache](https://github.com/tonycoco/heroku-buildpack-ember-cli#caching).

Does your app's build process depend on any external binaries? You may need a build hook then.
