### ISSUE TITLE
Heroku error: Push Rejected, no Cedar-supported app detected

### ISSUE THREAD

**Issue by alwaysautumn** [tonycoco/heroku-buildpack-ember-cli#39]
Hey,

I followed the instructions for deploying an ember-cli app to Heroku from the ember-cli main site, and had my push rejected. Any help on this would be appreciated. Thanks! :D

```
-----> Fetching custom git buildpack... done

 !     Push rejected, no Cedar-supported app detected

To git@heroku.com:realfeelz-ui.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'git@heroku.com:realfeelz-ui.git'
```

**Comment by gnapse** [comment]
I'm still getting this error:

```
$ heroku config:set BUILDPACK_URL=https://github.com/tonycoco/heroku-buildpack-ember-cli.git --app tecnet-webmovil                                                                ↵ 1
Setting config vars and restarting tecnet-webmovil... done, v3
BUILDPACK_URL: https://github.com/tonycoco/heroku-buildpack-ember-cli.git

$ git push heroku master
Counting objects: 25, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (25/25), done.
Writing objects: 100% (25/25), 473.23 KiB | 0 bytes/s, done.
Total 25 (delta 0), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote:
remote: -----> Fetching custom git buildpack... done
remote:
remote:  !     Push rejected, no Cedar-supported app detected
remote:
remote: Verifying deploy...
remote:
remote: !       Push rejected to tecnet-webmovil.
remote:
To https://git.heroku.com/tecnet-webmovil.git/
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/tecnet-webmovil.git/'

$ heroku config:get BUILDPACK_URL                                                                                                                                                 
 !    No app specified.
 !    Run this command from an app folder or specify which app to use with --app APP.

$ heroku config:get BUILDPACK_URL --app tecnet-webmovil                                                                                                                           
https://github.com/tonycoco/heroku-buildpack-ember-cli.git
```

As you can see in the last command, the buildpack url is properly set. Perhaps this has something to do with the ember/ember-cli version I'm using? I'm using ember-cli 0.1.6, ember 1.9.1, nodejs 0.10.35, npm 2.1.8

**Comment by tonycoco** [comment]
Those should be fine. Could you check the Heroku stack you're on? Only Cedar is supported. Check https://devcenter.heroku.com/articles/cedar-14-migration#upgrading-the-production-app-to-cedar-14 for details on how to upgrade the Heroku stack.

**Comment by gnapse** [comment]
I ended up deploying the app without the need of this buildpack, using [these instructions](http://blog.bguiz.com/2014/07/14/deploying-an-ember-cli-app-to-heroku/).

Could you point out the differences and advantages of using this buildpack? Also, what about the problem I posted above?

**Comment by tonycoco** [comment]
@gnapse the difference is that those instructions spin up a Node web server and run the application that way. This buildpack builds a production dist of your application and serves it with Nginx as a static application with the correct Nginx rewrites and configuration.

**Comment by dkrathi457** [comment]
remote: Compressing source files... done.
remote: Building source:
remote: 
remote: -----> Fetching custom git buildpack... failed
remote: 
remote:  !     Push rejected, error fetching custom buildpack
remote: 
remote: Verifying deploy...
remote: 
remote: !	Push rejected to demoos1.
remote: 
To https://git.heroku.com/demoos1.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/demoos1.git'
