### ISSUE TITLE
Allow API Proxy to Consume/Return any URL

### ISSUE THREAD

**Issue by drewcovi** [tonycoco/heroku-buildpack-ember-cli#49]
It would be great if we could make a request to a proxy endpoint (as it is currently) but pass a full request in the querystring.  This would leave our options fairly open-ended.  In node, I'm currently doing this by getting

```
req._parsedUrl.query;
```

**Comment by tonycoco** [comment]
@drewcovi got any idea how to do this in Nginx? Also, what are you doing this for and how is the request serialized in the query string?

**Comment by drewcovi** [comment]
Presently no additional work. Just passing the entire url and request querystring AS the querystring for the endpoint.

**Comment by tonycoco** [comment]
Not sure what the request is here if there's no additional work. What's the issue exactly?

**Comment by drewcovi** [comment]
Oh I meant that how I'm currently doing it with node, I'm not doing any serialization.

**Comment by john-kurkowski** [comment]
Be careful baking an [open redirect](https://www.owasp.org/index.php/Open_redirect) into this project.

**Comment by tonycoco** [comment]
@drewcovi any movement on this as a PR?

**Comment by tonycoco** [comment]
I'm closing this as I have no idea what it is I'm supposed to implement :) If someone wants to create a PR, that's cool by me, but this is not a feature I've seen the need for.
