### ISSUE TITLE
Issue deploying with ember-cli 0.1.7

### ISSUE THREAD

**Issue by amedr** [tonycoco/heroku-buildpack-ember-cli#50]
Not sure if I'm missing something, but I just tried to deploy an ember-cli 0.1.7 app to Heroku in production  mode, the deployment succeeds but the app keeps crashing, until now I have had to manually:

* Copy my `devDependencies` into `dependencies` in `package.json`
* Add bower package to `dependencies` in `package.json` because I noticed it wasn't being installed.

Yet the logs say that I need to run `bower install` somehow, I can't figure out how.

Anyway that's something that should be made during the deployment but it's not happening, maybe this is an incompatibility with the latest ember-cli?

I'm on a cedar-14 stack.

Thanks!

**Comment by tonycoco** [comment]
I'll take a look in a bit

**Comment by tonycoco** [comment]
@amedr Could you provide a repo that this does not work with? I can't reproduce it. Just ran my test app on cedar-14 with Ember CLI v0.1.7 (latest) and it worked fine.

**Comment by amedr** [comment]
@tonycoco just added you to my private repo. Could you provide an email for giving you access to Heroku as well?

**Comment by tonycoco** [comment]
Try to remove the temp bower and npm directories and save your dependency resolutions locally.
