### ISSUE TITLE
Deploying to Heroku results in an application size of 41MB

### ISSUE THREAD

**Issue by anandhs29** [tonycoco/heroku-buildpack-ember-cli#52]
I am not sure what I am doing incorrectly, so I thought I'd ask here. Running a build --environment=production, results in a dist size of 1.8MB. However, when I deploy to Ember, the final statement says: -----> Compressing... done, 41.3MB

Any idea why?

**Comment by tonycoco** [comment]
That's the size of the entire Heroku VM, not your application.
