### ISSUE TITLE
Make config variables available in environment.js?

### ISSUE THREAD

**Issue by thomchop** [tonycoco/heroku-buildpack-ember-cli#54]
My app depends on environment variables with I load from a local .env file with process.env.VAR_NAME in config/environment.js. I expected heroku config vars to be stores in a .env file, but that doesn't seem to be the case. Is there another way I can load config vars with ember-cli-dotenv? Thanks for the help.

**Comment by tonycoco** [comment]
Use Heroku's ENV vars...

https://devcenter.heroku.com/articles/config-vars

**Comment by thomchop** [comment]
Thanks, but that is what I tried. I was wondering why they weren't being picked up by ember-cli-dotenv with `process.env`. Is this issue unrelated to the buildpack?

**Comment by thomchop** [comment]
Nevermind. It's working now. I needed to trigger a build after setting the config vars.

**Comment by tonycoco** [comment]
No problem :+1:
