### ISSUE TITLE
Build fails with version 0.3.0 of ember-cli-app-version

### ISSUE THREAD

**Issue by gcollazo** [tonycoco/heroku-buildpack-ember-cli#57]
I was trying to deploy the latest version of emberaddons.com and the build was failing on heroku. I noticed the issue was related to v0.3.0 of ember-cli-app-version. After upgrading to v0.3.1 everything worked fine.

Thought that might be important to document since ember-cli comes with v0.3.0 of ember-cli-app-version.

**Comment by tonycoco** [comment]
I'll look into it. Thanks!

**Comment by gcollazo** [comment]
Closing, it has been fixed.

**Comment by tonycoco** [comment]
Cool, thanks.
