### ISSUE TITLE
double api-prefix necessary with dokku

### ISSUE THREAD

**Issue by dj-hedgehog** [tonycoco/heroku-buildpack-ember-cli#60]
I just deployed an Ember-CLI app with a Sails.js backend for the first time.
The Sails-backend serves via `http://<IP-Adress>:34523` my API-prefix is `api/v1` .
So I set `API_URL=http://<IP-Adress>:12345` and `API_PREFIX=/api/v1/` .

The Ember-Cli application would be available via `http://<IP-Adress>:12346`. It's making API requests to `http://<IP-Adress>:12346/api/v1/...` but the nginx of this buildpack is serving them via `http://<IP-Adress>:12346/api/v1/api/v1/...`

Can you imagine why that is happening?

**Comment by tonycoco** [comment]
I'll take a look, but I don't think I can support Dokku without having any experience with it.

**Comment by tonycoco** [comment]
Referencing #62 as well

**Comment by dj-hedgehog** [comment]
By the way, this issue is gone when using VHOSTS.

**Comment by tonycoco** [comment]
Referencing #66 too
