### ISSUE TITLE
Can't start container on dokku-alt but works on dokku

### ISSUE THREAD

**Issue by dj-hedgehog** [tonycoco/heroku-buildpack-ember-cli#61]
I'm using this buildpack to deploy my container to dokku which works as it's supposed to.
I've got a second host running dokku-alt and deployed my Ember-CLI application there as well.
Upon start the only log-message I get via `dokku logs <container` is:
`setuidgid: usage: setuidgid account child`

Do you know what might be the problem or how I can get more information regarding this problem?

**Comment by tonycoco** [comment]
I'm not familiar with the Dokku platform. I'll do some research tonight.

**Comment by dj-hedgehog** [comment]
that would be cool. It's basically a self-hosted mini-heroku using the same Procfiles etc.

**Comment by tonycoco** [comment]
Going to close this until I get some time to support Dokku.

**Comment by dj-hedgehog** [comment]
By the way, I'm successfully using the buildpack with dokku.
For dokku-alt issue happens with other buildpacks too and is tracked here:
https://github.com/dokku-alt/dokku-alt/issues/200

**Comment by chibipirate** [comment]
@tonycoco @dj-hedgehog any updates? I'm seeing this issue:
-----> Installing dependencies
remote: /tmp/buildpacks/custom/bin/compile: line 154:   118 Killed                  npm install --quiet --userconfig $build_dir/.npmrc 2>&1
remote:        119 Done                    | indent
To dokku@domain.com:app
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'dokku@domain.com:app'

**Comment by tonycoco** [comment]
I don't have dokku, nor do I really want to support it. If you put together a PR with the necessary changes, I'll gladly accept them :)
