### ISSUE TITLE
Multiple Ember-applications with only one Nginx?

### ISSUE THREAD

**Issue by dj-hedgehog** [tonycoco/heroku-buildpack-ember-cli#63]
I'd like to seperate my Ember-application into two applications. One for the admin-frontend and another one for the website itself.
Using your buildpack twice would be no problem but the additional Nginx-instance seems to be a bit of wasted resources.

Is it possible to use multiple Ember-applications with just one Nginx?

**Comment by tonycoco** [comment]
Short answer yes. But, this is a Heroku build pack and the use-case for it should be a single application. Closing in favor of multiple Heroku applications that can scale and live independently.
