### ISSUE TITLE
Heroku deployment fails

### ISSUE THREAD

**Issue by b-e-r-t-o** [tonycoco/heroku-buildpack-ember-cli#68]
Here is a brief overview of the error I'm getting: http://stackoverflow.com/questions/28913452/ember-cli-heroku-build-fails

remote: -----> Pruning cached bower dependencies not specified in bower.json

remote: -----> Caching node_modules directory for future builds

remote: -----> Cleaning up node-gyp and npm artifacts

remote: bower loader.js#1.0.1 mismatch Version declared in the json (0.0.0) is different than the resolved one (1.0.1)

remote: bower ember-qunit#0.2.8 invalid-meta ember-qunit is missing "main" entry in bower.json

remote: bower ember-data#1.0.0-beta.12 invalid-meta ember-data is missing "ignore" entry in bower.json

remote: bower ember#1.10.0 invalid-meta ember is missing "ignore" entry in bower.json

remote: bower ECONFLICT Unable to find suitable version for ember-data

remote:

remote: ! Push rejected, failed to compile Ember CLI app

**Comment by tonycoco** [comment]
Try running: `ember build` locally to resolve version dependencies.

**Comment by jme783** [comment]
I too am having this issue, and have seen others with similar problems. I can run `ember build` `npm install`, and `bower install` locally without any mention of version dependencies. Is there any other way to solve this?

**Comment by jme783** [comment]
For anyone running into this issue, the way to resolve version dependencies is to delete your entire `bower_components` directory first with `rm -rf bower_components`, then re-run `bower install` to install all of your bower dependencies from scratch. This helped me identify incompatible versions in my bower components.

**Comment by tonycoco** [comment]
I'll document this in the readme
