### ISSUE TITLE
Redirect non-www (naked domain) to www

### ISSUE THREAD

**Issue by JoshSmith** [tonycoco/heroku-buildpack-ember-cli#69]
I didn't want to go messing with nginx settings myself, so wondered if there's a way for us to redirect naked domains like `https://example.com` to `https://www.example.com`, perhaps with a flag of some sort.

**Comment by tonycoco** [comment]
Fixed with fd9068c678b630907eae7514682cb1f22a7f4ce0

**Comment by JoshSmith** [comment]
Awesome, you're a champ @tonycoco. :facepunch:

**Comment by tonycoco** [comment]
You're the one who keeps giving me ideas! :+1:
