### ISSUE TITLE
Make deploys faster

### ISSUE THREAD

**Issue by bartocc** [tonycoco/heroku-buildpack-ember-cli#70]
I was just wondering if deploys could be faster.
Right now, it approximately takes 6 minutes to deploy a bare ember-cli app to heroku.

**Comment by tonycoco** [comment]
The app deploy time should get significantly faster after the first deploy. It caches the Bower, NPM and Nginx builds. I'll run some performance tests myself to confirm.

**Comment by tonycoco** [comment]
Ran some tests:

    $ time git push heroku master

    ... Logging ...

    remote: Verifying deploy... done.
    To https://git.heroku.com/blllllaahhhhhh123.git
    2144362..caaa4d4  master -> master

    real     1m55.131s
    user     0m0.083s
    sys      0m0.161s

Looks like a second build only takes ~2 minutes. That's almost as fast as we can get. Since, the `ember build` itself takes close to 1 minute 20 seconds on Heroku with a small dyno.

**Comment by bartocc** [comment]
@tonycoco 

the second build logs this

remote: -----> Downloading and installing node
remote: -----> Downloading and installing nginx
remote: -----> Adding boot script
remote: -----> Copying configs
remote: -----> Restoring node_modules directory from cache
remote: -----> Pruning cached dependencies not specified in package.json
remote:        unbuild bower@1.3.12
remote: -----> Restoring bower_components directory from cache
remote: -----> Installing bower which is required by other dependencies

is this normal to download and install node, nginx and bower on each deploy ?

**Comment by tonycoco** [comment]
Node and Nginx get downloaded each time right now. This is how the official Node build pack worked, so I kept with that. I'll look into it and see if they have any updates to this process. Maybe we could cache those. But, that literally take 5/10 seconds. They are prebuilt binaries so they essentially just get unzipped and moved to a folder.

**Comment by bartocc** [comment]
ok.

and what about bower and all the bower dependencies ?

**Comment by tonycoco** [comment]
I'll look into it all. Reopening...

**Comment by tonycoco** [comment]
Bower and it's dependencies are cached already.

**Comment by johnhamelink** [comment]
:+1: would be good to see this buildpack running quicker. I think many people who are using heroku for this are using it to quickly prototype while they perhaps plan to use something like ember-cli-deploy later, and for that reason, I think it's especially important to have a nice fast deploy :smile:

**Comment by xtagon** [comment]
What is the benefit of the build step happening on Heroku's dyno rather than building locally and then pushing the already-built Ember app to Heroku? Is that alternative even possible?

**Comment by tonycoco** [comment]
The problem with that is there would need to be a something more than just the buildpack. Perhaps an ember-addon. I'll look into it but I'd rather keep this project a simple buildpack and just improve the build times within Heroku itself.

**Comment by romanbsd** [comment]
It looks like it re-installs the bower itself each time.

**Comment by harianus** [comment]
And this takes very long

```
Restoring node_modules directory from cache 
```

**Comment by natecox** [comment]
The slowest part of deployment for me is frequently 'verifying deploy'. I'm not entirely sure what kind of verification is happening, but every once in a while the verification process takes an extremely long period of time (upwards of half an hour).

**Comment by tonycoco** [comment]
Verification of deployment is done on the Heroku end... nothing we can do about that part from what I can tell. I'm working on a refactor of this on my spare time and will address the cache from node and ex-bower stuff.

**Comment by NathanJang** [comment]
It also appears to be pruning devDependencies before every build.

**Comment by GabKlein** [comment]
My avg is 6m 50s on each deployment. There are some very long steps as:
- Installing bower which is required by other dependencies
- Installing dependencies

**Comment by spyou** [comment]
Same here, our avarage deployment time is around 15 minutes. Would love to know what to do to make it faster.

It seems to reinstall everything all the time on each deploy.

**Comment by GabKlein** [comment]
@spyou Can you try with my branch?
`heroku buildpacks:set https://github.com/GabKlein/heroku-buildpack-ember-cli.git`

Let me know if you have any issue.

**Comment by tonycoco** [comment]
@GabKlein could you create a PR with those changes if they look good?

**Comment by GabKlein** [comment]
Hi @tonycoco, there is already a PR out there.
https://github.com/tonycoco/heroku-buildpack-ember-cli/pull/99

**Comment by tonycoco** [comment]
Closed #99 :beers: Cheers!

**Comment by GabKlein** [comment]
:+1:

**Comment by spyou** [comment]
@GabKlein the first deploy was much faster (somewhere near a couple of minutes VS 20). But now, I'm trying to deploy again, and I get 

```
remote: -----> Pruning cached dependencies not specified in package.json
remote:        unbuild bower@1.5.2
remote: -----> Pruning cached bower dependencies not specified in bower.json
remote:        /tmp/buildpack_ec132c393874afd297987c0b1714b60e/bin/compile: line 202: bower: command not found
remote: 
remote:  !     Push rejected, failed to compile Ember CLI app
```

Unfortunately, even reverting to the original buildpack now shows this error :/

**Comment by spyou** [comment]
@GabKlein for info, setting `heroku config:set REBUILD_ALL=true` seems to do the trick.

**Comment by GabKlein** [comment]
@spyou Thank you for this feedback! 
Did you notice any performance improvement?

**Comment by spyou** [comment]
Clearly yes. Massive improvements.
