### ISSUE TITLE
Build Error: JSParse Error

### ISSUE THREAD

**Issue by marvinosswald** [tonycoco/heroku-buildpack-ember-cli#73]
Hey guys,
What am I doing wrong ?

```
remote: -----> Building Ember CLI application production distribution
remote:        The package `ember-data` is not a properly formatted package, we have used a fallback lookup to resolve it at `/tmp/build_567d74112d5e3b6cbfd0e10cc2eef339/node_modules/ember-data`. This is generally caused by an addon not having a `main` entry point (or `index.js`).
remote:        version: 0.2.0
remote:        Could not find watchman, falling back to NodeWatcher for file system events
remote:        BuildingThe package `ember-data` is not a properly formatted package, we have used a fallback lookup to resolve it at `/tmp/build_567d74112d5e3b6cbfd0e10cc2eef339/node_modules/ember-data`. This is generally caused by an addon not having a `main` entry point (or `index.js`).
remote:        Building.Building..Building...Build failed.
remote:        Unexpected token: eof (undefined)
remote:        Error
remote:            at new JS_Parse_Error (/tmp/build_567d74112d5e3b6cbfd0e10cc2eef339/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/lib/parse.js:196:18)
remote:            at js_error (/tmp/build_567d74112d5e3b6cbfd0e10cc2eef339/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/lib/parse.js:204:11)
remote:            at croak (/tmp/build_567d74112d5e3b6cbfd0e10cc2eef339/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/lib/parse.js:678:41)
remote:            at token_error (/tmp/build_567d74112d5e3b6cbfd0e10cc2eef339/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/lib/parse.js:682:9)
remote:            at unexpected (/tmp/build_567d74112d5e3b6cbfd0e10cc2eef339/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/lib/parse.js:688:9)
remote:            at block_ (/tmp/build_567d74112d5e3b6cbfd0e10cc2eef339/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/lib/parse.js:1000:28)
remote:            at /tmp/build_567d74112d5e3b6cbfd0e10cc2eef339/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/lib/parse.js:974:25
remote:            at function_ (/tmp/build_567d74112d5e3b6cbfd0e10cc2eef339/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/lib/parse.js:979:15)
remote:            at expr_atom (/tmp/build_567d74112d5e3b6cbfd0e10cc2eef339/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/lib/parse.js:1187:24)
remote:            at maybe_unary (/tmp/build_567d74112d5e3b6cbfd0e10cc2eef339/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/lib/parse.js:1357:19)
remote: 
remote:  !     Push rejected, failed to compile Ember CLI app
```

**Comment by tonycoco** [comment]
Try `ember build` locally

**Comment by marvinosswald** [comment]
works like charm..

**Comment by tonycoco** [comment]
Could you make sure by running this from your project root:

    npm cache clean
    bower cache clean
    rm -rf node_modules bower_components dist tmp

And then do a:

    npm install
    bower install
    ember build

Does everything still work?

**Comment by marvinosswald** [comment]
Jap, still work.. I have an "postinstall": "bower install" in my package.json so I don't need to run a bower install manually shouldn't be a problem, should it ?

**Comment by tonycoco** [comment]
Might be the problem. Not sure.

**Comment by tonycoco** [comment]
Could you post your NPM `package.json` and `bower.json`

**Comment by marvinosswald** [comment]
@tonycoco thanks man for your advice.. removing the postinstall command fixed it. But now It appears my app can't access node, thought it should be there cause obviously it was there for install...

```
2015-03-23T16:52:06.459770+00:00 heroku[web.1]: Starting process with command `node index.js`
2015-03-23T16:52:08.354389+00:00 app[web.1]: bash: node: command not found
```
My best guess, it gets removed after building completed since u originally designed the build pack to work with nginx not a express solution.

**Comment by tonycoco** [comment]
Yeah, no Express app is used at all. It is essentially just building a static package of files and serving them with a Ngnix server. Not sure why you need the Node app spun up, but that is not what was intended for the buildpack.

**Comment by marvinosswald** [comment]
Yeah sure but I install it as dep so I should be able to run it with node installed. Basically I'm just trying to put frontend and backend together in my early stage beta phase to save some money.. But thanks anyway :) thats something I can solve by spliting them up again.

**Comment by tonycoco** [comment]
That would be something you'd have trouble doing on a single Heroku dyno/instance anyway. Might I suggest looking at the `API_URL` pattern we have in the buildpack and building the Node service on a separate Heroku instance? That would work and would keep costs down too. You could also make this work, I think, by running something in the buildpack's after hook. View the `README.md` for more information on all of this. The idea behind this buildpack is that you would never need to run the server here. That is a separate entity completely removed from your Ember application layer. They shouldn't mix, in our use-case.

It's just not something I want to have to support either :)
