### ISSUE TITLE
Incompatibility with ember-component-css

### ISSUE THREAD

**Issue by backspace** [tonycoco/heroku-buildpack-ember-cli#80]
Hey, thanks so much for this buildpack, it’s been very useful to me.

Some of us are [having trouble with `ember-component-css` styles not being applied on Heroku deployments](https://github.com/ebryn/ember-component-css/issues/51). I’ve done some [investigation](https://github.com/ebryn/ember-component-css/issues/51#issuecomment-101773971) and will continue with that, but let me know if you have some insight!

**Comment by tonycoco** [comment]
Have you tried building locally?

**Comment by backspace** [comment]
Yes, it works when I build locally and run it. I do think it’s probably a problem with the addon, though I don’t understand what it is. So you can close this if you don’t have any other suggestions.

**Comment by tonycoco** [comment]
Does that add-on rely on a binary?

**Comment by backspace** [comment]
I don’t think so, unless people are using it in combination with `ember-cli-sass` or another preprocessor. It seems like files are just written to the wrong places, or not merged properly.

I was able to get it working for a project just by adding logging statements to `ember-component-css` at the point where it appends to the Javascript asset file, so it doesn’t seem like a problem with your buildpack.
