### ISSUE TITLE
How to use force https with CloudFlare and Heroku

### ISSUE THREAD

**Issue by harianus** [tonycoco/heroku-buildpack-ember-cli#83]
I'm using CloudFlare for https in combination with Heroku. CloudFlare uses a slightly different name for redirect the http scheme; `$http_cf_visitor`. I also found that nginx filled `$http_cf_visitor` with `-` when it was not available. So that is why I test for `$http_cf_visitor ~* 'http'`. Nginx does not support the `and ` operator, so that is why this code is so terrible long.

It works when you replace the `<% if ENV["FORCE_HTTPS"] && ENV["FORCE_HTTPS"] == "true" %>` section in your `nginx.conf.erb` with this:

```erb
<% if ENV["FORCE_HTTPS"] && ENV["FORCE_HTTPS"] == "true" %>
  <%# Set default value for cloudflare %>
  set $cloudflare NO;

  <%# This matches http and https ($http_cf_visitor: {"scheme": "https"})%>
  if ($http_cf_visitor ~* 'http') {
    set $cloudflare YES;
  }
  <%# Redirect when is matches "http" (with quotes) %>
  if ($http_cf_visitor ~* '"http"') {
    return 301 https://$host$request_uri;
  }

  <%# Only redirect when cloudflare is false and heroku is true %>
  set $cloudflare_heroku "${cloudflare}";
  <%# This matches http and https %>
  if ($http_x_forwarded_proto ~* 'http') {
    set $cloudflare_heroku "${cloudflare_heroku}YES";
  }
  <%# Redirect when is matches not "https" (without quotes) %>
  if ($http_x_forwarded_proto !~* 'https') {
    set $cloudflare_heroku "${cloudflare_heroku}HTTP";
  }
  if ($cloudflare_heroku = NOYESHTTP) {
    return 301 https://$host$request_uri;
  }
<% end %>
```

I think this solution should be somewhere in this repo. As part of `nginx.conf.erb` seems a little overkill, but maybe in the docs @tonycoco? If so I'll create a pull request.

**Comment by xtagon** [comment]
@harianus Thanks for sharing the solution, it helped me out. :+1:

**Comment by tonycoco** [comment]
Yeah, please PR the `README.md`... I'll merge it once I check it over.

**Comment by harianus** [comment]
Is this only for the `README.md` or can I add it to the default `nginx.conf.erb`?

**Comment by tonycoco** [comment]
Oh, then, I'd say let it rip. Let's put it in the `nginx.conf.erb`

**Comment by tonycoco** [comment]
(*both*)
