### ISSUE TITLE
ember not found/devDependencies not installed

### ISSUE THREAD

**Issue by NathanJang** [tonycoco/heroku-buildpack-ember-cli#87]
I'm using [Heroku's built-in multi-buildpack function](https://devcenter.heroku.com/articles/using-multiple-buildpacks-for-an-app) because I want to serve a custom express app.

```bash
$ heroku buildpacks 
=== APPNAME Buildpack URLs
1. https://github.com/tonycoco/heroku-buildpack-ember-cli.git
2. https://github.com/heroku/heroku-buildpack-nodejs.git
```

```bash
$ heroku config 
=== APPNAME Config Vars
DATABASE_URL:                 ...
HEROKU_POSTGRESQL_BRONZE_URL: ...
NODE_ENV:                     production
```

```bash
$ git push -f heroku heroku:master # I'm working on a branch named heroku
...
remote: -----> Cleaning up node-gyp and npm artifacts
remote: bower ember-simple-auth#0.8.0     invalid-meta ember-simple-auth is missing "ignore" entry in bower.json
remote: bower ember#1.13.2                invalid-meta ember is missing "ignore" entry in bower.json
remote: -----> Caching bower_components directory for future builds
remote: -----> Building Ember CLI application production distribution
remote: /tmp/buildpack20150721-162-131pwjv/bin/compile: line 208: node_modules/ember-cli/bin/ember: No such file or directory
remote: 
remote:  !     Push rejected, failed to compile Ember CLI app
remote: 
remote: Verifying deploy....
remote: 
remote: !   Push rejected to APPNAME.
remote: 
To https://git.heroku.com/APPNAME.git
 ! [remote rejected] heroku -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/APPNAME.git'
```
```
{
  "name": "appname",
  "version": "0.0.0",
  "description": "DESCRIPTION",
  "private": true,
  "directories": {
    "doc": "doc",
    "test": "tests"
  },
  "scripts": {
    "start": "ember server",
    "build": "ember build",
    "test": "ember test"
  },
  "repository": "",
  "engines": {
    "node": "~0.12.7"
  },
  "dependencies": {
    "express": "^4.13.1",
    "morgan": "^1.5.3"
  },
  "devDependencies": {
    "broccoli-asset-rev": "^2.0.2",
    "broccoli-jscs": "0.0.22",
    "ember-cli": "^0.2.7",
    "ember-cli-app-version": "0.3.3",
    "ember-cli-babel": "^5.0.0",
    "ember-cli-content-security-policy": "^0.4.0",
    "ember-cli-dependency-checker": "^1.0.0",
    "ember-cli-htmlbars": "^0.7.9",
    "ember-cli-ic-ajax": "0.1.2",
    "ember-cli-inject-live-reload": "^1.3.0",
    "ember-cli-less": "^1.3.3",
    "ember-cli-qunit": "0.3.14",
    "ember-cli-simple-auth": "0.8.0-beta.3",
    "ember-cli-uglify": "^1.0.1",
    "ember-data": "1.0.0-beta.19.2",
    "ember-disable-proxy-controllers": "^1.0.0",
    "ember-export-application-global": "^1.0.2",
    "glob": "^5.0.10"
  }
}
```

I've already tried the troubleshooting steps and purging the cache/resetting the repo with [heroku-repo](https://github.com/heroku/heroku-repo). The app builds fine locally.

**Comment by NathanJang** [comment]
It appears to have been fixed by
```bash
$ heroku config:set NPM_CONFIG_PRODUCTION=false
```
This is in the [node.js buildpack's README](https://github.com/heroku/heroku-buildpack-nodejs#enable-or-disable-devdependencies-installation). I believe that this has nothing to do with the fact that I'm using a multi-step buildpack process, because the node.js buildpack is run after this one anyway.

I think the issue is that including ember-cli in devDependencies without setting this variable led to it not being installed. Perhaps something should be mentioned in the documentation.

**Comment by tonycoco** [comment]
The NodeJS and EmberCLI buildpacks are very similar. Lots of confusion might occur when using that multi-buildpacks plugin for Heroku. I'm not sure I've ever done anything like that. The idea behind this buildpack was to only serve the Ember app. Have you thought of serving the Express app on a different app deployment instance of Heroku?

**Comment by NathanJang** [comment]
I need it on the same instance because of my budget. Correct me if I'm wrong, but wouldn't 2 separate instances charge me twice the amount?

I added the ember buildpack because I need something to actually compile the ember app. The node buildpack only installs things and starts the server process.

**Comment by tonycoco** [comment]
Yeah, I'm not sure I want to support this type of double serving from the EmberCLI build pack. Yes, it most likely will cost you more, though Heroku's free instances should run this build pack just fine (or, the express server for that matter)... If needed, a PR is more than welcome :)
