### ISSUE TITLE
Slug too big

### ISSUE THREAD

**Issue by xypaul** [tonycoco/heroku-buildpack-ember-cli#95]
I've got a really small ember cli app, but even then the slug is too big for the free plan
```
Compiled slug size: 322.4MB is too large (max is 300MB).
```
Any suggestions what I could do to work around it?

**Comment by tonycoco** [comment]
Hmm, that's odd. Let me try with my test apps and see what's up.

**Comment by xypaul** [comment]
@tonycoco had any chance to look at it yet?

**Comment by tonycoco** [comment]
Both tests did not have that problem. Can you post your `bower.json` and `package.json`?
